[[questions]]
    text = """Can you compute modulus of 2 floating point numbers? If yes, how?"""
    positive = 1
    negative = 1
    repl = "https://repl.it/@arpitbbhayani/floating-point-mod"

    [[questions.options]]
        text = """You cannot compute it programatically."""

    [[questions.options]]
        code = """x % y"""

    [[questions.options]]
        code = """fmod(x, y)"""
        correct = true

    [[questions.options]]
        code = """mod(x, y)"""


[[questions]]
    text = """Predict the output of the program given below"""
    code = """
#include <stdio.h>
int main()
{
   printf("5.3 %% 1.2 = %f\n", 5.3 % 1.2);
   return 0;
}"""
    positive = 1
    negative = 1
    repl = "https://repl.it/@arpitbbhayani/floating-point-mod-1"

    [[questions.options]]
        text = """Compilation Error"""
        correct = true

    [[questions.options]]
        code = """0"""

    [[questions.options]]
        code = """0.500000"""

    [[questions.options]]
        code = """4.1"""
